fix US29
WildCodeSchool/orleans-php-202009-project-aviron pull request #117
Opened 2020-12-29 07:43 UTC by Aurelie-F

2020-12-29 10:05 UTC, JulieRebeyrolle approved these changes, later dismissed

2020-12-30 13:44 UTC, sblondeau requested changes

2020-12-30 13:44 UTC, sblondeau commented on templates/subscriber/filter.html.twig
> +            <div class="col flex-column align-items-start justify-content-end">
pourquoi n'utilise tu pas les helper {{form }} plutot que le label / select directement ? 
je pense que tu te compliques là ?

2020-12-30 13:54 UTC, Aurelie-F commented on templates/subscriber/filter.html.twig
> +            <div class="col flex-column align-items-start justify-content-end">
Parce que le message d’erreur est attaché au label avec Bootstrap et comme mon formulaire est en ligne pour chaque type de filtre, j’ai du le gérer comme ça pour afficher le message d’erreur sous le champ...

2021-01-04 08:29 UTC, sblondeau requested changes

2021-01-04 08:29 UTC, sblondeau commented on templates/subscriber/filter.html.twig
> +            <div class="col flex-column align-items-start justify-content-end">
tu as un form_theme bootstrap_horizontal si c'est ça que tu veux faire ? (mais tu n'es pas obligé d'utiliser le theme bootstrap automatique, mais dans ce cas il faut ajouter les classe et div qui vont bien à la main). Mais dans tous les cas tu peux par les helper form et tu peux récupérer indépendamment {{form_label }} {{form_widget }} et {{ form_errors }}
y a peut etre un truc qui m'echappe mais j'ai pas l'impression

2021-01-04 09:41 UTC, JulieRebeyrolle submitted a review, later dismissed

2021-01-04 14:12 UTC, sblondeau commented on templates/subscriber/filter.html.twig
> +        {% if not form.vars.valid %}
je ne suis pas sûr là, pour moi si tu utilises le error_bubbling, ici tu n'as plus qu'à faire un {{ form_errors(form) }} non ? que tu mets éventuelelment dans un div class="alert alert-danger"... 
ça ne fonctionne pas comme ça ?

2021-01-04 14:24 UTC, Aurelie-F commented on templates/subscriber/filter.html.twig
> +        {% if not form.vars.valid %}
si... dure la reprise !

2021-01-04 16:59 UTC, JulieRebeyrolle approved these changes

2021-01-05 08:39 UTC, sblondeau approved these changes

2021-01-05 08:39 UTC, merged