S03 US30 number adherent filter
WildCodeSchool/orleans-php-202009-project-aviron pull request #128
Opened 2021-01-04 09:42 UTC by Aurelie-F

2021-01-04 09:52 UTC, JulieRebeyrolle submitted a review, later dismissed

2021-01-04 14:35 UTC, sblondeau requested changes

2021-01-04 14:35 UTC, sblondeau commented on translations/messages.fr.yaml
>  form.filter.fromSeason: 'De'
ah, par contre ne te prend pas la tete avec de la traduction là, le site sera tjs en FR donc pas besoin de mettre en place l'internationalisation, tu vas perdre du temps

2021-01-04 16:57 UTC, JulieRebeyrolle approved these changes, later dismissed

2021-01-05 08:40 UTC, sblondeau requested changes
pense à supprimer le fichier de traduction

2021-01-05 14:40 UTC, sblondeau approved these changes

2021-01-05 14:40 UTC, merged