S03 US32 gender filter
WildCodeSchool/orleans-php-202009-project-aviron pull request #142
Opened 2021-01-05 10:38 UTC by Aurelie-F

2021-01-05 11:04 UTC, BarbaraGonthier approved these changes, later dismissed

2021-01-05 14:48 UTC, sblondeau requested changes

2021-01-05 14:48 UTC, sblondeau commented on src/Entity/Subscriber.php
> +    public const GENDER = ['H', 'F'];
est ce que ça ne fonctionnerait pas de faire plutot 
const GENDER = ['Homme' => 'H', 'Femme' => 'F'];
tu l'utiliserais tjs dans ton @Assert\Choice mais également dans ton ChoiceType dans le form

2021-01-05 14:48 UTC, sblondeau commented on src/Form/FilterType.php
> +                'choices' => [
ici 'choices' => Filter::GENDER

2021-01-06 08:27 UTC, sblondeau approved these changes

2021-01-06 08:27 UTC, merged