S03 us55 data color
WildCodeSchool/orleans-php-202009-project-aviron pull request #154
Opened 2021-01-06 13:47 UTC by BarbaraGonthier

2021-01-06 14:11 UTC, MatthieuBardet approved these changes

2021-01-06 19:40 UTC, sblondeau requested changes

2021-01-06 19:40 UTC, sblondeau commented on assets/styles/app.scss
> +@for $i from 9 through 12 {
va falloir m'expliquer un peu ce bout de code et ces classes bizarres :D

2021-01-07 06:15 UTC, BarbaraGonthier commented on assets/styles/app.scss
> +@for $i from 9 through 12 {
c'est pour conditionner la couleur d'affichage des informations (category, licence, renewal) dans les tableaux, comme il y a avait sur le site d'origine, pour identifier visuellement par couleur tous les renouvellements, les reprises, ou les senior-23, les junior-9 etc.
et puis la boucle c'était pour pouvoir l'utiliser au mions une fois sur un projet ^^'

2021-01-07 08:30 UTC, sblondeau approved these changes

2021-01-07 08:30 UTC, merged