import subscribers in db
WildCodeSchool/orleans-php-202009-project-aviron pull request #177
Opened 2021-01-07 12:38 UTC by JulieRebeyrolle

2021-01-07 12:46 UTC, BarbaraGonthier approved these changes, later dismissed

2021-01-07 14:18 UTC, sblondeau requested changes

2021-01-07 14:18 UTC, sblondeau commented on src/Service/CsvImport.php
> +                        'ISO-8859-1',
le iconv c'est que tu as des pb d'encodage de certains caractères ?
si c'est vraiment utilie, faudrait que ce soit fait quand tu récupère ton csvstring peut-etre ?

2021-01-07 14:18 UTC, sblondeau commented on src/Service/CsvImport.php
> +                $subscriber = $this->subscriberRepository->findOneBy([
ok c'est bien, mais tu peux optimiser
                 $subscriber = $this->subscriberRepository->findOneBy licence ??  $this->subscriberRepository->findOneBy nom/prenom/datenaissance ?? new Subscriber();

Et ensuite, tu fais tes setXXX() => ça t'évite de répeter la partie hydratation.

2021-01-07 21:36 UTC, MatthieuBardet approved these changes

2021-01-08 08:38 UTC, sblondeau approved these changes

2021-01-08 08:39 UTC, merged