S04_fix_export-filters
WildCodeSchool/orleans-php-202009-project-aviron pull request #187
Opened 2021-01-11 06:31 UTC by BarbaraGonthier

2021-01-11 08:28 UTC, Aurelie-F approved these changes, later dismissed

2021-01-11 08:45 UTC, sblondeau requested changes

2021-01-11 08:45 UTC, sblondeau commented on src/Controller/SubscriberController.php
> +        $filters->setSeasonCategory($filtersArray['seasonCategory'] ?? null);
pour la lisibilité, vu que tes setter renvoient l'objet lui meme, tu peux faire
$filters 
    ->setXXX()
    ->setYYY()
    ->setZZZ()...
 plutot que de remettre $filters à chaque fois

2021-01-11 09:50 UTC, BarbaraGonthier commented on src/Controller/SubscriberController.php
> +        $filters->setSeasonCategory($filtersArray['seasonCategory'] ?? null);
car si je les ajoute j'ai cette erreur par phpstorm : 'void' method 'setFromAdherent' result used

2021-01-12 07:58 UTC, sblondeau approved these changes

2021-01-12 07:58 UTC, merged