S00 initialisation projet
WildCodeSchool/orleans-php-202009-project-aviron pull request #2
Opened 2020-12-03 15:28 UTC by JulieRebeyrolle

2020-12-03 15:30 UTC, MatthieuBardet submitted a review, later dismissed

2020-12-03 16:14 UTC, sblondeau requested changes

2020-12-03 16:14 UTC, sblondeau commented on templates/home/index.html.twig
> +        <img class="box-shadow" src="https://media.giphy.com/media/jTCA7mJocIW4DUZHwC/giphy.gif" alt="Dewey dancing">
enlève l'image de Dewey (aussi mignon soit-il :D) pour avoir une page propre :p

2020-12-04 08:13 UTC, MatthieuBardet approved these changes

2020-12-04 08:42 UTC, sblondeau approved these changes

2020-12-04 08:42 UTC, merged