S4 us56 color property
WildCodeSchool/orleans-php-202009-project-aviron pull request #201
Opened 2021-01-11 10:03 UTC by BarbaraGonthier

2021-01-11 11:07 UTC, JulieRebeyrolle submitted a review, later dismissed

2021-01-12 08:08 UTC, sblondeau requested changes

2021-01-12 08:08 UTC, sblondeau commented on src/Entity/Category.php
> +     * @ORM\Column(type="string", length=255, nullable=true)
ajoute un @Assert\Regex pour vérif que ça a un format de couleur hexa, en gérant des longeurs de 7 et 9 carac car l'opacité est optionnelle

2021-01-12 09:37 UTC, sblondeau approved these changes

2021-01-12 09:38 UTC, merged