S04 us52 subscription import data from csv
WildCodeSchool/orleans-php-202009-project-aviron pull request #202
Opened 2021-01-11 10:49 UTC by JulieRebeyrolle

2021-01-11 15:17 UTC, BarbaraGonthier submitted a review, later dismissed

2021-01-12 08:34 UTC, sblondeau requested changes

2021-01-12 08:34 UTC, sblondeau commented on src/Service/CsvImport.php
> +            $subscriptionDateArray = explode('/', $csvLine['DATE DE SAISIE']);
tu pourrais avoir une méthode private qui prend une date "jj/'mm/yyyy' et la tranforme en un Datetime (car tu refais la meme chose 2 fois là)

2021-01-12 08:34 UTC, sblondeau commented on src/Service/CsvImport.php
>              if ($subscriber == null) {
utilise plutot "instanceof Subscriber" c'est plus parlant je trouve

2021-01-12 08:34 UTC, sblondeau commented on src/Service/CsvImport.php
>                      $subscriber = new Subscriber();
instanceof Subscriber plutot que ==null

2021-01-12 08:34 UTC, sblondeau commented on src/Service/CsvImport.php
> +                    ->setSubscriptionDate($subscriptionDate)
les 3 dernier set sont les meme dans le if et le elseif, je pense que tu peux faire en sorte de ne pas les répéter

2021-01-13 08:23 UTC, sblondeau approved these changes

2021-01-13 08:23 UTC, merged