S04 US58 filter summary
WildCodeSchool/orleans-php-202009-project-aviron pull request #213
Opened 2021-01-11 15:18 UTC by Aurelie-F

2021-01-11 15:45 UTC, BarbaraGonthier submitted a review, later dismissed

2021-01-12 11:32 UTC, sblondeau submitted a review, later dismissed

2021-01-12 15:26 UTC, JulieRebeyrolle approved these changes, later dismissed

2021-01-12 15:29 UTC, JulieRebeyrolle submitted a review, later dismissed

2021-01-13 08:35 UTC, sblondeau requested changes

2021-01-13 08:35 UTC, sblondeau commented on templates/subscriber/index.html.twig
> +                <button onClick="window.history.back();" type="button" class="btn btn-primary mb-4">
nope, pas de onClick.  fais un simple retour vers le form ("Faire une nouvelle recherche") 
 l'utilisateur fera lui meme un retour avec son navigateur, mais history.back est pas super fiable si l'user à désactivé le JS par ex.

2021-01-18 11:07 UTC, sblondeau requested changes

2021-01-18 11:07 UTC, sblondeau commented on src/Controller/SubscriberController.php
> +        $filter->setSeasonStatus($seasonRepository->findOneBy([], ['name' => 'DESC']));
je comprends pas à quoi set tes seasonRepository->findOneBy([], ['name' => 'DESC']) vu que tu as ajouter un tri directement dans le formType (ce qui est bien) ?

2021-01-18 11:13 UTC, Aurelie-F commented on src/Controller/SubscriberController.php
> +        $filter->setSeasonStatus($seasonRepository->findOneBy([], ['name' => 'DESC']));
pour que ce soit la dernière saison qui soit sélectionnée par défaut (et par id ça n'allait pas)

2021-01-18 14:31 UTC, sblondeau approved these changes

2021-01-18 14:31 UTC, merged