Fix status entity
WildCodeSchool/orleans-php-202009-project-aviron pull request #223
Opened 2021-01-12 22:14 UTC by JulieRebeyrolle

2021-01-13 07:50 UTC, BarbaraGonthier submitted a review, later dismissed

2021-01-13 09:54 UTC, sblondeau requested changes

2021-01-13 09:54 UTC, sblondeau commented on src/DataFixtures/StatusFixtures.php
> +/*    public const TRANSFER = ['Transfert' => 'T'];
code commenté => gateau ! :p

2021-01-13 09:54 UTC, sblondeau commented on src/Entity/Status.php
> +     * @ORM\Column(type="string", length=100)
ajoute des assert

2021-01-16 09:34 UTC, JulieRebeyrolle commented on src/DataFixtures/StatusFixtures.php
> +/*    public const TRANSFER = ['Transfert' => 'T'];
oops

2021-01-18 08:24 UTC, MatthieuBardet approved these changes, later dismissed

2021-01-18 09:58 UTC, MatthieuBardet approved these changes

2021-01-18 11:08 UTC, sblondeau approved these changes

2021-01-18 11:08 UTC, merged