S04 US35 first subscription filter
WildCodeSchool/orleans-php-202009-project-aviron pull request #234
Opened 2021-01-18 14:15 UTC by Aurelie-F

2021-01-18 14:55 UTC, MatthieuBardet submitted a review, later dismissed

2021-01-18 17:46 UTC, sblondeau requested changes

2021-01-18 17:46 UTC, sblondeau commented on src/Service/FirstSubscription.php
> +    public function filterWithCategory(array $subscribers, Category $category, bool $stillRegistered): array
je pense que tu pourrais optimiser ce code 
- peut-etre utiliser un array_filter()
- tes conditions me semblent cumulables (plutot que de faire plusieurs if, utiliser des && ou des || )
- tu pourrais aussi n'avoir qu'une seule méthode filterWith(array $subscribers, LabelInterface $entity, , bool $stillRegistered) 
 
 => je ne suis pas certain que ça fonctionne je n'ai pas testé et le code est assez complexe, donc si c'est pas possible pas grave, c'est "que" de l'optimisation, mais c'est intéressant que tu essaies d'aller un peu plus loin pour être plus DRY, ça me semble possible.

2021-01-19 12:39 UTC, MatthieuBardet approved these changes

2021-01-19 14:54 UTC, sblondeau approved these changes

2021-01-19 14:54 UTC, merged