Fix issue #337
WildCodeSchool/orleans-php-202009-project-aviron pull request #355
Opened 2021-01-28 11:09 UTC by Aurelie-F

2021-01-28 14:00 UTC, BarbaraGonthier submitted a review, later dismissed

2021-01-28 14:05 UTC, sblondeau requested changes

2021-01-28 14:05 UTC, sblondeau commented on templates/subscriber/filter.html.twig
> +            {% if display == 'licences' %}Récapitulatif des types de licences{% endif %}
on pourrait pas faire direct un 
            Récapitulatif des {{display}} 
on perd le "types de" pour licences mais pas très grave non ?

2021-01-29 08:23 UTC, sblondeau approved these changes

2021-01-29 08:23 UTC, merged