Fix first and second season import
WildCodeSchool/orleans-php-202009-project-aviron pull request #390
Opened 2021-02-05 16:30 UTC by JulieRebeyrolle

2021-02-06 14:02 UTC, MatthieuBardet approved these changes

2021-02-07 21:20 UTC, sblondeau requested changes

2021-02-07 21:20 UTC, sblondeau commented on src/Controller/HomeController.php
> +                $previousSeason = $seasonRepository->findBy([], ['name' => 'DESC'], 1, 1)[0]->getName();
tu veux pas faire un findOneBy plutot ?

2021-02-07 21:25 UTC, JulieRebeyrolle commented on src/Controller/HomeController.php
> +                $previousSeason = $seasonRepository->findBy([], ['name' => 'DESC'], 1, 1)[0]->getName();
Je fais comment pour l'offset ?

2021-02-08 11:24 UTC, merged