S01 us49 subscriber season
WildCodeSchool/orleans-php-202009-project-aviron pull request #48
Opened 2020-12-09 15:54 UTC by BarbaraGonthier

2020-12-09 15:55 UTC, BarbaraGonthier commented
a fix will be made later to had some fake data with fictures

2020-12-09 16:00 UTC, MatthieuBardet submitted a review, later dismissed

2020-12-09 16:12 UTC, sblondeau requested changes

2020-12-09 16:12 UTC, sblondeau commented on migrations/Version20201209155252.php
> +}
je ne devrais avoir qu'un fichier de migration par PR, drop ta table subscritpion et season, efface ces migrations
et relance un make:migration pour n'avoir qu'un fichier, car là j'ai tout l'historique de ta creation, ça fait creer une table subscription_season puis ça l'efface pour recreer une table subscription ;-)

2020-12-09 16:12 UTC, sblondeau commented on templates/subscriber/index.html.twig
>                          <tr>
je ne vois pas la condition qui gère les "trous" dans les colones (là peut etre que votre affichage fonctionne car vous n'avez pas de données avec des "trous" ? (à gérer coté fixtures peut-etre ! )

2020-12-09 18:31 UTC, BarbaraGonthier commented on templates/subscriber/index.html.twig
>                          <tr>
dans cette US on ne gère que les licenciés rattachés aux saisons en questions, dans une prochaine US on gèrera les licenciés qui n'ont pas toutes les saisons

2020-12-09 20:16 UTC, Aurelie-F submitted a review, later dismissed
c'est good

2020-12-10 07:13 UTC, Aurelie-F approved these changes
C’est good

2020-12-10 08:15 UTC, sblondeau approved these changes

2020-12-10 08:15 UTC, merged