S01 us27 licence
WildCodeSchool/orleans-php-202009-project-aviron pull request #52
Opened 2020-12-10 14:05 UTC by Aurelie-F

2020-12-10 14:09 UTC, MatthieuBardet approved these changes, later dismissed

2020-12-10 14:29 UTC, MatthieuBardet approved these changes, later dismissed

2020-12-10 16:15 UTC, sblondeau requested changes

2020-12-10 16:15 UTC, sblondeau commented on src/Controller/LicenceController.php
> +class LicenceController extends AbstractController
ok tout est nickel, j'ai juste un doute
est-ce qu'on a vraiment besoin d'un LicenceController et d'une vue dédiée ? au final je me disais que tout pouvais etre géré par la vue subscriber, en faisant varié juste un paramètre. Car sinon ça fait énormément de répétitions

2020-12-11 08:51 UTC, MatthieuBardet approved these changes, later dismissed

2020-12-11 08:54 UTC, sblondeau requested changes

2020-12-11 08:54 UTC, sblondeau commented on src/Controller/SubscriberController.php
> +        return $this->render('licence/index.html.twig', [
pas plutot subscriber/index.html.twig ? vu que tu as plus le LicenceController / index() ?

2020-12-11 09:01 UTC, Aurelie-F commented on src/Controller/SubscriberController.php
> +        return $this->render('licence/index.html.twig', [
oui... c'est la fin de semaine...

2020-12-11 09:02 UTC, MatthieuBardet approved these changes

2020-12-11 09:06 UTC, sblondeau approved these changes

2020-12-11 09:06 UTC, merged