S02 us2 login
WildCodeSchool/orleans-php-202009-project-aviron pull request #82
Opened 2020-12-15 16:12 UTC by BarbaraGonthier

2020-12-15 16:43 UTC, MatthieuBardet requested changes

2020-12-15 16:43 UTC, MatthieuBardet commented on assets/styles/login.scss
> +@media screen and (max-width: 768px) {
Regarde du côté de d-none sur bootstrap pour éviter la media query

2020-12-15 22:22 UTC, MatthieuBardet submitted a review, later dismissed

2020-12-16 12:34 UTC, sblondeau requested changes

2020-12-16 12:34 UTC, sblondeau commented on assets/styles/login.scss
> +    background-image: url("http://ana.faucheux.info/download/prise_d-eau_hollandais.JPG");
ne prends pas tes images en ligne mais télécharge dans le dossier assets/images

2020-12-16 12:54 UTC, MatthieuBardet approved these changes

2020-12-16 13:02 UTC, sblondeau approved these changes

2020-12-16 13:02 UTC, merged